#############################################################################
# Makefile for building: Co-Simulation
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  Co-Simulation.pro
# Template: subdirs
# Command: D:\QT\Qt5.9.4\5.9.4\msvc2015\bin\qmake.exe -o Makefile Co-Simulation.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\QT\Qt5.9.4\5.9.4\msvc2015\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\QT\Qt5.9.4\5.9.4\msvc2015\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\QT\Qt5.9.4\5.9.4\msvc2015\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-XmlUtil \
		sub-SockUtil \
		sub-MsHandler \
		sub-SbSHandler \
		sub-MtController \
		sub-SimTest \
		sub-MidSoftUI \
		sub-DecisionAlth \
		sub-Algorithm \
		sub-SbsSoftUI \
		sub-PowerHandler


sub-XmlUtil-qmake_all:  FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && $(MAKE) -f Makefile qmake_all
sub-XmlUtil: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-XmlUtil-make_first: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-XmlUtil-all: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-XmlUtil-clean: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-XmlUtil-distclean: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-XmlUtil-install_subtargets: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-XmlUtil-uninstall_subtargets: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-SockUtil-qmake_all:  FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && $(MAKE) -f Makefile qmake_all
sub-SockUtil: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-SockUtil-make_first: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-SockUtil-all: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-SockUtil-clean: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-SockUtil-distclean: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-SockUtil-install_subtargets: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-SockUtil-uninstall_subtargets: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MsHandler-qmake_all:  FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && $(MAKE) -f Makefile qmake_all
sub-MsHandler: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MsHandler-make_first: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MsHandler-all: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MsHandler-clean: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MsHandler-distclean: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MsHandler-install_subtargets: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MsHandler-uninstall_subtargets: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-SbSHandler-qmake_all:  FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && $(MAKE) -f Makefile qmake_all
sub-SbSHandler: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-SbSHandler-make_first: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-SbSHandler-all: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-SbSHandler-clean: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-SbSHandler-distclean: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-SbSHandler-install_subtargets: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-SbSHandler-uninstall_subtargets: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MtController-qmake_all:  FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && $(MAKE) -f Makefile qmake_all
sub-MtController: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MtController-make_first: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MtController-all: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MtController-clean: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MtController-distclean: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MtController-install_subtargets: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MtController-uninstall_subtargets: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-SimTest-qmake_all:  FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && $(MAKE) -f Makefile qmake_all
sub-SimTest: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-SimTest-make_first: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-SimTest-all: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-SimTest-clean: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-SimTest-distclean: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-SimTest-install_subtargets: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-SimTest-uninstall_subtargets: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MidSoftUI-qmake_all:  FORCE
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	cd MidSoftUI\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && $(MAKE) -f Makefile qmake_all
sub-MidSoftUI: FORCE
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MidSoftUI-make_first: FORCE
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MidSoftUI-all: FORCE
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MidSoftUI-clean: FORCE
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MidSoftUI-distclean: FORCE
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MidSoftUI-install_subtargets: FORCE
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MidSoftUI-uninstall_subtargets: FORCE
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-DecisionAlth-qmake_all:  FORCE
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	cd DecisionAlth\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && $(MAKE) -f Makefile qmake_all
sub-DecisionAlth: FORCE
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-DecisionAlth-make_first: FORCE
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-DecisionAlth-all: FORCE
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-DecisionAlth-clean: FORCE
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-DecisionAlth-distclean: FORCE
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-DecisionAlth-install_subtargets: FORCE
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-DecisionAlth-uninstall_subtargets: FORCE
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Algorithm-qmake_all:  FORCE
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	cd Algorithm\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && $(MAKE) -f Makefile qmake_all
sub-Algorithm: FORCE
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Algorithm-make_first: FORCE
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Algorithm-all: FORCE
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Algorithm-clean: FORCE
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Algorithm-distclean: FORCE
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Algorithm-install_subtargets: FORCE
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Algorithm-uninstall_subtargets: FORCE
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-SbsSoftUI-qmake_all:  FORCE
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	cd SbsSoftUI\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && $(MAKE) -f Makefile qmake_all
sub-SbsSoftUI: FORCE
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-SbsSoftUI-make_first: FORCE
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-SbsSoftUI-all: FORCE
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-SbsSoftUI-clean: FORCE
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-SbsSoftUI-distclean: FORCE
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-SbsSoftUI-install_subtargets: FORCE
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-SbsSoftUI-uninstall_subtargets: FORCE
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-PowerHandler-qmake_all:  FORCE
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	cd PowerHandler\ && $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && $(MAKE) -f Makefile qmake_all
sub-PowerHandler: FORCE
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-PowerHandler-make_first: FORCE
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-PowerHandler-all: FORCE
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-PowerHandler-clean: FORCE
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-PowerHandler-distclean: FORCE
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-PowerHandler-install_subtargets: FORCE
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-PowerHandler-uninstall_subtargets: FORCE
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: Co-Simulation.pro D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\win32-msvc\qmake.conf D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\spec_pre.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\common\angle.conf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\common\msvc-desktop.conf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\qconfig.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3danimation.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3danimation_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dcore.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dextras.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dinput.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquick.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickanimation.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3drender.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axbase.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axserver.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_charts.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_charts_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_concurrent.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_core.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_core_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_datavisualization.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_datavisualization_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_dbus.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_designer.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_designer_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_egl_support_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_fb_support_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_gamepad.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_gui.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_gui_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_help.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_help_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_location.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_location_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_multimedia.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_network.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_network_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_nfc.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_opengl.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_positioning.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_printsupport.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qml.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qml_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qmltest.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quick.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quick_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_scxml.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_sensors.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_serialbus.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_serialport.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_sql.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_sql_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_svg.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_svg_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_testlib.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_theme_support_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_uitools.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_webchannel.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_websockets.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_webview.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_webview_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_widgets.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_winextras.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_xml.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_xml_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\qt_functions.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\qt_config.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\win32-msvc\qmake.conf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\spec_post.prf \
		.qmake.stash \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\exclusive_builds.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\common\msvc-version.conf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\toolchain.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\default_pre.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\win32\default_pre.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\resolve_config.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\exclusive_builds_post.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\default_post.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\qml_debug.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\precompile_header.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\warn_on.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\qmake_use.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\file_copies.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\win32\windows.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\testcase_targets.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\exceptions.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\yacc.prf \
		D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\lex.prf \
		Co-Simulation.pro
	$(QMAKE) -o Makefile Co-Simulation.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\spec_pre.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\common\angle.conf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\common\msvc-desktop.conf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\qconfig.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3danimation.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3danimation_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dcore.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dextras.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dinput.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquick.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickanimation.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickscene2d.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3drender.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_accessibility_support_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axbase.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axserver.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_charts.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_charts_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_concurrent.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_core.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_core_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_datavisualization.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_datavisualization_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_dbus.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_designer.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_designer_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_egl_support_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_fb_support_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_gamepad.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_gui.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_gui_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_help.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_help_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_location.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_location_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_multimedia.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_network.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_network_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_nfc.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_opengl.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_positioning.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_printsupport.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qml.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qml_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qmltest.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quick.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quick_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_scxml.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_sensors.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_serialbus.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_serialport.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_sql.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_sql_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_svg.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_svg_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_testlib.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_theme_support_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_uitools.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_webchannel.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_websockets.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_webview.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_webview_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_widgets.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_winextras.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_xml.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_xml_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\qt_functions.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\qt_config.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\win32-msvc\qmake.conf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\spec_post.prf:
.qmake.stash:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\exclusive_builds.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\common\msvc-version.conf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\toolchain.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\default_pre.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\win32\default_pre.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\resolve_config.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\exclusive_builds_post.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\default_post.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\qml_debug.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\precompile_header.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\warn_on.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\qmake_use.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\file_copies.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\win32\windows.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\testcase_targets.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\exceptions.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\yacc.prf:
D:\QT\Qt5.9.4\5.9.4\msvc2015\mkspecs\features\lex.prf:
Co-Simulation.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Co-Simulation.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-XmlUtil-qmake_all sub-SockUtil-qmake_all sub-MsHandler-qmake_all sub-SbSHandler-qmake_all sub-MtController-qmake_all sub-SimTest-qmake_all sub-MidSoftUI-qmake_all sub-DecisionAlth-qmake_all sub-Algorithm-qmake_all sub-SbsSoftUI-qmake_all sub-PowerHandler-qmake_all FORCE

make_first: sub-XmlUtil-make_first sub-SockUtil-make_first sub-MsHandler-make_first sub-SbSHandler-make_first sub-MtController-make_first sub-SimTest-make_first sub-MidSoftUI-make_first sub-DecisionAlth-make_first sub-Algorithm-make_first sub-SbsSoftUI-make_first sub-PowerHandler-make_first  FORCE
all: sub-XmlUtil-all sub-SockUtil-all sub-MsHandler-all sub-SbSHandler-all sub-MtController-all sub-SimTest-all sub-MidSoftUI-all sub-DecisionAlth-all sub-Algorithm-all sub-SbsSoftUI-all sub-PowerHandler-all  FORCE
clean: sub-XmlUtil-clean sub-SockUtil-clean sub-MsHandler-clean sub-SbSHandler-clean sub-MtController-clean sub-SimTest-clean sub-MidSoftUI-clean sub-DecisionAlth-clean sub-Algorithm-clean sub-SbsSoftUI-clean sub-PowerHandler-clean  FORCE
distclean: sub-XmlUtil-distclean sub-SockUtil-distclean sub-MsHandler-distclean sub-SbSHandler-distclean sub-MtController-distclean sub-SimTest-distclean sub-MidSoftUI-distclean sub-DecisionAlth-distclean sub-Algorithm-distclean sub-SbsSoftUI-distclean sub-PowerHandler-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-XmlUtil-install_subtargets sub-SockUtil-install_subtargets sub-MsHandler-install_subtargets sub-SbSHandler-install_subtargets sub-MtController-install_subtargets sub-SimTest-install_subtargets sub-MidSoftUI-install_subtargets sub-DecisionAlth-install_subtargets sub-Algorithm-install_subtargets sub-SbsSoftUI-install_subtargets sub-PowerHandler-install_subtargets FORCE
uninstall_subtargets: sub-XmlUtil-uninstall_subtargets sub-SockUtil-uninstall_subtargets sub-MsHandler-uninstall_subtargets sub-SbSHandler-uninstall_subtargets sub-MtController-uninstall_subtargets sub-SimTest-uninstall_subtargets sub-MidSoftUI-uninstall_subtargets sub-DecisionAlth-uninstall_subtargets sub-Algorithm-uninstall_subtargets sub-SbsSoftUI-uninstall_subtargets sub-PowerHandler-uninstall_subtargets FORCE

sub-XmlUtil-debug:
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-SockUtil-debug:
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MsHandler-debug:
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-SbSHandler-debug:
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MtController-debug:
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-SimTest-debug:
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MidSoftUI-debug:
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-DecisionAlth-debug:
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Algorithm-debug:
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-SbsSoftUI-debug:
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-PowerHandler-debug:
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-XmlUtil-debug sub-SockUtil-debug sub-MsHandler-debug sub-SbSHandler-debug sub-MtController-debug sub-SimTest-debug sub-MidSoftUI-debug sub-DecisionAlth-debug sub-Algorithm-debug sub-SbsSoftUI-debug sub-PowerHandler-debug

sub-XmlUtil-release:
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-SockUtil-release:
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MsHandler-release:
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-SbSHandler-release:
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MtController-release:
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-SimTest-release:
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MidSoftUI-release:
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-DecisionAlth-release:
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Algorithm-release:
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-SbsSoftUI-release:
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-PowerHandler-release:
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-XmlUtil-release sub-SockUtil-release sub-MsHandler-release sub-SbSHandler-release sub-MtController-release sub-SimTest-release sub-MidSoftUI-release sub-DecisionAlth-release sub-Algorithm-release sub-SbsSoftUI-release sub-PowerHandler-release

sub-XmlUtil-check:
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-SockUtil-check:
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MsHandler-check:
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-SbSHandler-check:
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MtController-check:
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-SimTest-check:
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MidSoftUI-check:
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-DecisionAlth-check:
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Algorithm-check:
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-SbsSoftUI-check:
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-PowerHandler-check:
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-XmlUtil-check sub-SockUtil-check sub-MsHandler-check sub-SbSHandler-check sub-MtController-check sub-SimTest-check sub-MidSoftUI-check sub-DecisionAlth-check sub-Algorithm-check sub-SbsSoftUI-check sub-PowerHandler-check

sub-XmlUtil-benchmark:
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-SockUtil-benchmark:
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SockUtil\SockUtil.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MsHandler-benchmark:
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MsHandler\MsHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-SbSHandler-benchmark:
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MtController-benchmark:
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MtController\MtController.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-SimTest-benchmark:
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SimTest\SimTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MidSoftUI-benchmark:
	@if not exist MidSoftUI\ mkdir MidSoftUI\ & if not exist MidSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MidSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\MidSoftUI\MidSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-DecisionAlth-benchmark:
	@if not exist DecisionAlth\ mkdir DecisionAlth\ & if not exist DecisionAlth\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DecisionAlth\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\DecisionAlth\DecisionAlth.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Algorithm-benchmark:
	@if not exist Algorithm\ mkdir Algorithm\ & if not exist Algorithm\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Algorithm\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\Algorithm\Algorithm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-SbsSoftUI-benchmark:
	@if not exist SbsSoftUI\ mkdir SbsSoftUI\ & if not exist SbsSoftUI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SbsSoftUI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\SbsSoftUI\SbsSoftUI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-PowerHandler-benchmark:
	@if not exist PowerHandler\ mkdir PowerHandler\ & if not exist PowerHandler\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd PowerHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\VSQtDIR\QT5.9.4\Co-Simulation-MSVC2015-UI\Co-Simulation\PowerHandler\PowerHandler.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-XmlUtil-benchmark sub-SockUtil-benchmark sub-MsHandler-benchmark sub-SbSHandler-benchmark sub-MtController-benchmark sub-SimTest-benchmark sub-MidSoftUI-benchmark sub-DecisionAlth-benchmark sub-Algorithm-benchmark sub-SbsSoftUI-benchmark sub-PowerHandler-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

