#############################################################################
# Makefile for building: Co-Simulation
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  Co-Simulation.pro
# Template: subdirs
# Command: D:\Qt\Qt5.8.0\5.8\mingw53_32\bin\qmake.exe -o Makefile Co-Simulation.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Qt\Qt5.8.0\5.8\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-XmlUtil \
		sub-SockUtil \
		sub-MsHandler \
		sub-SbSHandler \
		sub-MtController \
		sub-SimTest


sub-XmlUtil-qmake_all:  FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd XmlUtil\ && $(MAKE) -f Makefile qmake_all
sub-XmlUtil: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-XmlUtil-make_first: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-XmlUtil-all: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-XmlUtil-clean: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-XmlUtil-distclean: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-XmlUtil-install_subtargets: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-XmlUtil-uninstall_subtargets: FORCE
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-SockUtil-qmake_all:  FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd SockUtil\ && $(MAKE) -f Makefile qmake_all
sub-SockUtil: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-SockUtil-make_first: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-SockUtil-all: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-SockUtil-clean: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-SockUtil-distclean: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-SockUtil-install_subtargets: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-SockUtil-uninstall_subtargets: FORCE
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MsHandler-qmake_all:  FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd MsHandler\ && $(MAKE) -f Makefile qmake_all
sub-MsHandler: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MsHandler-make_first: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MsHandler-all: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MsHandler-clean: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MsHandler-distclean: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MsHandler-install_subtargets: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MsHandler-uninstall_subtargets: FORCE
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-SbSHandler-qmake_all:  FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd SbSHandler\ && $(MAKE) -f Makefile qmake_all
sub-SbSHandler: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-SbSHandler-make_first: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-SbSHandler-all: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-SbSHandler-clean: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-SbSHandler-distclean: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-SbSHandler-install_subtargets: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-SbSHandler-uninstall_subtargets: FORCE
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MtController-qmake_all:  FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd MtController\ && $(MAKE) -f Makefile qmake_all
sub-MtController: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MtController-make_first: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MtController-all: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MtController-clean: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MtController-distclean: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MtController-install_subtargets: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MtController-uninstall_subtargets: FORCE
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-SimTest-qmake_all:  FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd SimTest\ && $(MAKE) -f Makefile qmake_all
sub-SimTest: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-SimTest-make_first: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-SimTest-all: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-SimTest-clean: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-SimTest-distclean: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-SimTest-install_subtargets: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-SimTest-uninstall_subtargets: FORCE
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: Co-Simulation.pro D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/spec_pre.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/qdevice.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/device_config.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/common/angle.conf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/qconfig.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/qt_functions.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/qt_config.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/spec_post.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/toolchain.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/default_pre.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/resolve_config.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/default_post.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/qml_debug.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/win32/rtti.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/precompile_header.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/warn_on.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/qmake_use.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/file_copies.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/win32/windows.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/testcase_targets.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/exceptions.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/yacc.prf \
		D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/lex.prf \
		Co-Simulation.pro
	$(QMAKE) -o Makefile Co-Simulation.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/spec_pre.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/qdevice.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/device_config.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/common/angle.conf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/qconfig.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/qt_functions.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/qt_config.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/spec_post.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/toolchain.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/default_pre.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/resolve_config.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/default_post.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/qml_debug.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/win32/rtti.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/precompile_header.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/warn_on.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/qmake_use.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/file_copies.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/win32/windows.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/testcase_targets.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/exceptions.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/yacc.prf:
D:/Qt/Qt5.8.0/5.8/mingw53_32/mkspecs/features/lex.prf:
Co-Simulation.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Co-Simulation.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-XmlUtil-qmake_all sub-SockUtil-qmake_all sub-MsHandler-qmake_all sub-SbSHandler-qmake_all sub-MtController-qmake_all sub-SimTest-qmake_all FORCE

make_first: sub-XmlUtil-make_first sub-SockUtil-make_first sub-MsHandler-make_first sub-SbSHandler-make_first sub-MtController-make_first sub-SimTest-make_first  FORCE
all: sub-XmlUtil-all sub-SockUtil-all sub-MsHandler-all sub-SbSHandler-all sub-MtController-all sub-SimTest-all  FORCE
clean: sub-XmlUtil-clean sub-SockUtil-clean sub-MsHandler-clean sub-SbSHandler-clean sub-MtController-clean sub-SimTest-clean  FORCE
distclean: sub-XmlUtil-distclean sub-SockUtil-distclean sub-MsHandler-distclean sub-SbSHandler-distclean sub-MtController-distclean sub-SimTest-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-XmlUtil-install_subtargets sub-SockUtil-install_subtargets sub-MsHandler-install_subtargets sub-SbSHandler-install_subtargets sub-MtController-install_subtargets sub-SimTest-install_subtargets FORCE
uninstall_subtargets: sub-XmlUtil-uninstall_subtargets sub-SockUtil-uninstall_subtargets sub-MsHandler-uninstall_subtargets sub-SbSHandler-uninstall_subtargets sub-MtController-uninstall_subtargets sub-SimTest-uninstall_subtargets FORCE

sub-XmlUtil-debug:
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-SockUtil-debug:
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MsHandler-debug:
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-SbSHandler-debug:
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MtController-debug:
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-SimTest-debug:
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-XmlUtil-debug sub-SockUtil-debug sub-MsHandler-debug sub-SbSHandler-debug sub-MtController-debug sub-SimTest-debug

sub-XmlUtil-release:
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-SockUtil-release:
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MsHandler-release:
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-SbSHandler-release:
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MtController-release:
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-SimTest-release:
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-XmlUtil-release sub-SockUtil-release sub-MsHandler-release sub-SbSHandler-release sub-MtController-release sub-SimTest-release

sub-XmlUtil-check:
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-SockUtil-check:
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MsHandler-check:
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-SbSHandler-check:
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MtController-check:
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-SimTest-check:
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-XmlUtil-check sub-SockUtil-check sub-MsHandler-check sub-SbSHandler-check sub-MtController-check sub-SimTest-check

sub-XmlUtil-benchmark:
	@if not exist XmlUtil\ mkdir XmlUtil\ & if not exist XmlUtil\ exit 1
	cd XmlUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\XmlUtil\XmlUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-SockUtil-benchmark:
	@if not exist SockUtil\ mkdir SockUtil\ & if not exist SockUtil\ exit 1
	cd SockUtil\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SockUtil\SockUtil.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MsHandler-benchmark:
	@if not exist MsHandler\ mkdir MsHandler\ & if not exist MsHandler\ exit 1
	cd MsHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MsHandler\MsHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-SbSHandler-benchmark:
	@if not exist SbSHandler\ mkdir SbSHandler\ & if not exist SbSHandler\ exit 1
	cd SbSHandler\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SbSHandler\SbSHandler.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MtController-benchmark:
	@if not exist MtController\ mkdir MtController\ & if not exist MtController\ exit 1
	cd MtController\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\MtController\MtController.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-SimTest-benchmark:
	@if not exist SimTest\ mkdir SimTest\ & if not exist SimTest\ exit 1
	cd SimTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtPro\Co-Simulation\SimTest\SimTest.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-XmlUtil-benchmark sub-SockUtil-benchmark sub-MsHandler-benchmark sub-SbSHandler-benchmark sub-MtController-benchmark sub-SimTest-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

